name: Deploy Swagger UI

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
