name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Rebuild ESLint
        run: npm rebuild eslint --force
        working-directory: backend

      - name: Run ESLint
        run: npm run lint
        working-directory: backend

      - name: Generate Swagger JSON
        run: npm run swagger:generate
        working-directory: backend

      - name: Disable Jekyll
        run: touch backend/public/.nojekyll

      - name: Upload static site artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: backend/public
