name: CI and Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Rebuild ESLint
        run: npm rebuild eslint --force
        working-directory: backend

      - name: Run ESLint
        run: npm run lint
        working-directory: backend

      - name: Generate Swagger JSON
        run: npm run swagger:generate
        working-directory: backend

      - name: Disable Jekyll
        run: touch backend/public/.nojekyll

      - name: Upload Swagger UI for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: backend/public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
