name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Reinstall ESLint (fix Windows permission issue)
        run: npm rebuild eslint --force

      - name: Run ESLint
        run: npm run lint

      - name: Generate Swagger JSON
        run: npm run swagger:generate

      - name: Disable Jekyll
        run: touch public/.nojekyll

      - name: Upload static site artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
