name: Deploy Swagger UI

on:
  workflow_run:
    workflows: ["Backend CI"]
    types: [completed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Download artifact from Backend CI
        uses: actions/download-artifact@v4
        with:
          name: github-Pages
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
