name: Deploy Swagger UI

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          run-id: ${{ github.event.workflow_run.id }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
